### ISSUE TITLE
ProcBot: ActionType HandOff not available in method player_action

### ISSUE THREAD

**Issue by Drefsante** [njustesen/botbowl#162]
Sequence that leads to this problem is for example:
- bot declares Start_HANDOFF action
- then moves player and moves on ball to pick-up;

Then method `player_action` is called, and inside this method if you call:
`game.get_available_actions()`
then only MOVE and END_PLAYER_TURN actions are available, not HANDOFF.
Notice that at this step, if you use a MOVE action on the player you want to hand-off, then it works (the hand-off will be executed). But if you use a HANDOFF action it doesn't work (even if next the player).
Problem is not visible for human user.

**Comment by njustesen** [comment]
I guess it shouldn't show MOVE actions that are actually HANDOFF actions to adjacent players. It's only a move if involves moving (and potentially handing off).

I'll look into this!

**Comment by njustesen** [comment]
Closing this because the behavior is as designed. 

If pathfinding is enabled, then all actions that involves moving AND something else is a move action*. 
If pathfinding is disabled, you can either move or do something else if it doesn't involve moving.

* this design is perhaps not the most intuitive but requires a significant redesign to change. You can always check if a move action has a handoff_roll associated to its path.

**Comment by Drefsante** [comment]
Ok thanks, indeed there is way to bypass the problem...

**Comment by mrbermell** [comment]
If I'm not mistaken this issue has been solved. @Drefsante, can you confirm and close it?

**Comment by Drefsante** [comment]
Yes thanks! I have just tested.
